UPS = 120

WINDOW_WIDTH = 500
WINDOW_HEIGHT = 500

TILE_SIZE = 40
MAP_TILE_WIDTH = 32
MAP_TILE_HEIGHT = 18

GAME_NAME = "Tile map game"

HALF_TILE_SIZE = TILE_SIZE // 2
MAP_TILE_HALF_WIDTH = MAP_TILE_WIDTH // 2
MAP_TILE_HALF_HEIGHT = MAP_TILE_HEIGHT // 2
MAP_PIXEL_WIDTH = MAP_TILE_WIDTH * TILE_SIZE
MAP_PIXEL_HEIGHT = MAP_TILE_HEIGHT * TILE_SIZE
MAP_PIXEL_HALF_WIDTH = MAP_PIXEL_WIDTH // 2
MAP_PIXEL_HALF_HEIGHT = MAP_PIXEL_HEIGHT // 2
