UPS = 60

GAME_NAME = "Tile map game"

TILE_SIZE = 40
MAP_TILE_SCALE = 4
MAP_TILE_WIDTH_RATIO = 16
MAP_TILE_HEIGHT_RATIO = 9
MAP_TILE_WIDTH = MAP_TILE_WIDTH_RATIO * MAP_TILE_SCALE
MAP_TILE_HEIGHT = MAP_TILE_HEIGHT_RATIO * MAP_TILE_SCALE

FULLSCREEN = False

# Windowed settings (if FULLSCREEN=False)
WINDOW_SCALE = TILE_SIZE * 2
WINDOW_WIDTH_RATIO = 16
WINDOW_HEIGHT_RATIO = 9
WINDOW_WIDTH = WINDOW_WIDTH_RATIO * WINDOW_SCALE
WINDOW_HEIGHT = WINDOW_HEIGHT_RATIO * WINDOW_SCALE

if __name__ == "__main__":
    exit()
